import { Sacramento } from "next/font/google";
import "./globals.css";
import Logo from "@/components/common/logo";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Logo />
        {children}
      </body>
    </html>
  );
}
